server:
  port: 8080
spring:
  profiles:
    active: develop
  flyway:
    enabled: false
    baseline-on-migrate: true
    validate-on-migrate: true
    locations: classpath:/db/migration
    out-of-order: false